import CpnAddBtn from './add-btn/AddBtn';
import CpnAlarmItem from './alarm-item/AlarmItem';
import CpnClockItem from './clock-item/ClockItem';
import CpnCountDown from './count-down/CountDown';
import CpnDisplayTime from './display-time/DisplayTime';
import CpnLayout from './layout/Layout';
import CpnMask from './mask/Mask';
import CpnMenubar from './menubar/Menubar';
import CpnNumberSlideSelector from './number-slide-selector/NumberSlideSelector';
import CpnSeconder from './seconder/Seconder';
import CpnSwiper from './swiper/Swiper';
import CpnSwitch from './switch/Switch';
import CpnTab from './tab/Tab';
import CpnTabbar from './tabbar/Tabbar';
import CpnTimeSettingPanel from './time-setting-panel/TimeSettingPanel';

export const AddBtn = CpnAddBtn;
export const AlarmItem = CpnAlarmItem;
export const ClockItem = CpnClockItem;
export const CountDown = CpnCountDown;
export const DisplayTime = CpnDisplayTime;
export const Layout = CpnLayout;
export const Mask = CpnMask;
export const Menubar = CpnMenubar;
export const NumberSlideSelector = CpnNumberSlideSelector;
export const Seconder = CpnSeconder;
export const Swiper = CpnSwiper;
export const Switch = CpnSwitch;
export const Tab = CpnTab;
export const Tabbar = CpnTabbar;
export const TimeSettingPanel = CpnTimeSettingPanel;
